apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: uber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: pullsecret-ghcr
      containers:
        - name: api
          image: ghcr.io/johnmayou/uber/api:sha-7efa38794699fc9186228343429319950082c83c
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          ports:
            - containerPort: 8080
