apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: uber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: hello-world
          image: ghcr.io/johnmayou/uber/hello-world:latest
          ports:
            - containerPort: 8080
