apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: uber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      imagePullSecrets:
        - name: pullsecret-ghcr
      containers:
        - name: user
          image: ghcr.io/johnmayou/uber/services/user:sha-2a9784a304626b25ec2fb455d19074fcd24aaaa8
          ports:
            - containerPort: 8080
