apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip
  namespace: uber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip
  template:
    metadata:
      labels:
        app: trip
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: trip
          image: ghcr.io/johnmayou/uber/services/trip:latest
          ports:
            - containerPort: 8080
