apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: uber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      imagePullSecrets:
        - name: pullsecret-ghcr
      containers:
        - name: auth
          image: ghcr.io/johnmayou/uber/services/auth:sha-2a9784a304626b25ec2fb455d19074fcd24aaaa8
          ports:
            - containerPort: 8080
