apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: uber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      imagePullSecrets:
        - name: pullsecret-ghcr
      containers:
        - name: auth
          image: ghcr.io/johnmayou/uber/services/auth:sha-2098cf0c8b6e685795bb8caac6035ee8b0a6c711
          ports:
            - containerPort: 8080
