apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: uber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      imagePullSecrets:
        - name: pullsecret-ghcr
      containers:
        - name: auth
          image: ghcr.io/johnmayou/uber/services/auth:sha-f26d3aeafda0bed119281c58f436d0ef0b64ea77
          ports:
            - containerPort: 8080
